execute:
  - SilverStripe\Gatsby\GraphQL\ModelLoader
resolvers:
  - SilverStripe\Gatsby\GraphQL\DataObjectResolver
  - SilverStripe\Gatsby\GraphQL\SyncResolver
  - SilverStripe\Gatsby\GraphQL\SchemaResolver
modelConfig:
  DataObject:
    type_formatter: 'SilverStripe\Core\ClassInfo::shortName'
    base_fields:
      ID: ID!
      HashID: String
      TypeAncestry: '[[String]]'
    plugins:
      versioning: false
      inheritance:
        useUnionQueries: false
    operations:
      read:
        plugins:
          filter: true
          paginateList: false
          readVersion: false
      readOne:
        plugins:
          readVersion: false
      delete:
        plugins:
          unpublishOnDelete: false
