---
Name: silverstripe-gatsby-config
---
SilverStripe\ORM\DataObject:
  extensions:
    - SilverStripe\Gatsby\Extensions\DataObjectExtension
    - SilverStripe\Gatsby\Extensions\SiteTreeExtension
SilverStripe\Core\Injector\Injector:
  SilverStripe\Gatsby\Handler\ContentUpdateHandler:
    properties:
      url: '`CONTENT_UPDATE_URL`'
