---
Name: silverstripe-gatsby-config
---
SilverStripe\ORM\DataObject:
  extensions:
    - SilverStripe\Gatsby\Extensions\DataObjectExtension
    - SilverStripe\Gatsby\Extensions\SiteTreeExtension
SilverStripe\Assets\File:
  extensions:
    - SilverStripe\Gatsby\Extensions\FileExtension
SilverStripe\Admin\Forms\UsedOnTable:
  extensions:
    - SilverStripe\Gatsby\Extensions\UsedOnTableExtension
