---
Name: silverstripe-gatsby-config
---
SilverStripe\Assets\File:
  extensions:
    - SilverStripe\Gatsby\Extensions\UsedFileExtension
SilverStripe\Admin\Forms\UsedOnTable:
  extensions:
    - SilverStripe\Gatsby\Extensions\UsedOnTableExtension
